#!/bin/bash
cp=$(find -name "org.eclipse.equinox.launcher_*.jar" | sort | tail -1);
java -Dorg.osgi.service.http.port=8888 -cp $cp org.eclipse.equinox.launcher.Main -consolelog -console -initialize -noExit
